### ISSUE TITLE
files_sharding 404

### ISSUE THREAD

**Issue by pierreozoux** [deic-dk/science_cloud#1]
I found your repo searching for a way to shard my nextcloud, ad the link is 404, any chance you could fix that?

Thanks!

**Comment by deltafunction** [comment]
Thanks for your interest. I've made the repository public.

Please notice that this app depends on several others as well as a theme. Also, it will induce a  refactoring of your service (no shared files via webdav). So, all in all, a rather large undertaking.

If you choose to go ahead, we're happy to help you.
