### ISSUE TITLE
Could not authorise Nextcloud desktop app

### ISSUE THREAD

**Issue by sgjche** [deic-dk/science_cloud#4]
When I tried to authorise Nextcloud desktop app (Mac), it returns me:

![image](https://user-images.githubusercontent.com/40319159/151169556-412c43b6-aeb2-4301-9720-d3b3e8856f3f.png)

Also doesn't work with my iPhone.
Does anyone know what I should do?

Cheers!

**Comment by deltafunction** [comment]
There were changes in new version of the clients. Works now. If you still have problems, get in touch on our support email (support@...).
