### ISSUE TITLE
Cannot Sync Due to Invalid Modification Time

### ISSUE THREAD

**Issue by pbvahlst** [deic-dk/science_cloud#7]
On Windows NextCloud client v 3.6.2 it keep getting the error "Cannot sync due to invalid modification time". I seems that this is something which needs to fixed on the server https://github.com/nextcloud/desktop/wiki/How-to-fix-the-error-invalid-or-negative-modification-date

**Comment by deltafunction** [comment]
We just implemented a fix. Please try again and let us know. You may 
have to exit your client and start it again.

**Comment by pbvahlst** [comment]
yes that seemed to have fixed the problem. Thanks.
