### ISSUE TITLE
I have lost my menu on the left hand side

### ISSUE THREAD

**Issue by vilocha** [deic-dk/science_cloud#8]
Hiya,

I cannot enter my space as the dropdown menu on the left has dissapeared. Can anybody help?

Vicente

**Comment by deltafunction** [comment]
Hi Vicente,

Thanks for using ScienceData.

It sounds like you lost a group membership - but I need more details to look into it. It's probably better if you write us directly on our support email.

Best regards,
Frederik

**Comment by vilocha** [comment]
Frederik,
Can you please pass me your support email? I will share with you an exchange of emails I shared today with Denmark in order to get this reactivated. They sent me a new invite for membership and still not working - it is quite frustrating :(
Best,
Vicente

**Comment by vilocha** [comment]
Hi Frederik,

I guess it is cloud@deic.dk? I will write there

Best,
Vicente

**Comment by vilocha** [comment]
Hi again,

Actually, I wrote to that email four days ago and still have not been contacted.
(I found the same email address by other means)

Best,
Vicente

**Comment by deltafunction** [comment]
On Chrome, clear the cache to get the newest JavaScript files from the server.
